services:
  auth.provider.mycustomauth:
    class: tsumego\customsso\auth\provider\mycustomauth
    arguments:
      - '@request'
      - '@dbal.conn'
      - '@config'
      - '@user'
      - '%core.root_path%'
      - '%core.php_ext%'
    tags:
      - { name: auth.provider }
