#ddev-generated
# Remove the line above if you don't want this file to be overwritten when you run
# ddev get ddev/ddev-selenium-standalone-firefox
#
# This file comes from https://github.com/ddev/ddev-selenium-standalone-firefox
#
version: '3.6'
services:
  selenium-firefox:
    image: seleniarm/standalone-firefox:109.0-geckodriver-0.32
    container_name: ddev-${DDEV_SITENAME}-selenium-firefox
    expose:
      #      The internal noVNC port, which operates over HTTP so it can be exposed
      #      through the router.
      - 7900
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      # Exposed to 7901 to play nice with chrome addon.
      - HTTPS_EXPOSE=7901:7900
      - HTTP_EXPOSE=7911:7900
    external_links:
      - ddev-router:tsumego.ddev.site
      - ddev-router:test.tsumego.ddev.site
    # To enable VNC access for traditional VNC clients like macOS "Screen Sharing",
    # uncomment the following two lines.
    #ports:
    #  - "5901:5900"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"

  web:
    links:
      - selenium-firefox
